# Generated by Django 2.1.7 on 2019-03-29 18:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric, dashes, and underscores allowed', regex='^[a-zA-Z0-9_\\-]+$')])),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('image', models.ImageField(height_field='height', upload_to='club_photos/', width_field='width')),
                ('description', models.CharField(max_length=5000)),
                ('link', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('url', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric, dashes, and underscores allowed', regex='^[a-zA-Z0-9_\\-]+$')])),
            ],
        ),
        migrations.AddField(
            model_name = 'lab',
            name='prerequisites',
            field=models.ManyToManyField(related_name='labs', to='labs.Prerequisite')
        ),
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('url', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric, dashes, and underscores allowed', regex='^[a-zA-Z0-9_\\-]+$')])),
            ],
        ),
        migrations.AddField(
            model_name='lab',
            name='recommendeds',
            field=models.ManyToManyField(related_name='labs', to='labs.Recommended'),
        ),
    ]
