# Generated by Django 2.1.7 on 2019-05-03 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='admins',
            field=models.ManyToManyField(related_name='labs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lab',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
