# Generated by Django 2.1.7 on 2019-05-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_auto_20190503_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='lab_photos/', width_field='width'),
        ),
    ]
