# Generated by Django 2.1.7 on 2019-04-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_auto_20190401_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='prerequisites',
            new_name='prerequisite',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='recommendeds',
            new_name='recommended',
        ),
        migrations.AlterField(
            model_name='lab',
            name='image',
            field=models.ImageField(height_field='height', upload_to='lab_photos/', width_field='width'),
        ),
    ]
