# Generated by Django 2.1.7 on 2019-05-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_auto_20190503_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='height',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='width',
        ),
        migrations.AlterField(
            model_name='lab',
            name='description',
            field=models.CharField(default='This club page has not yet been filled out.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='lab',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lab_photos/'),
        ),
    ]
