# Generated by Django 2.1.7 on 2019-04-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_auto_20190405_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='prerequisite',
            new_name='prerequisites',
        ),
    ]
