# Generated by Django 2.1.7 on 2019-05-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_auto_20190509_1923'),
        ('labs', '0004_auto_20190509_1849'),
    ]

    operations = [
    ]
