# Generated by Django 2.1.7 on 2019-05-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_merge_20190509_2215'),
        ('labs', '0005_auto_20190509_2222'),
    ]

    operations = [
    ]
