# Generated by Django 2.1.7 on 2019-05-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_auto_20190512_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='recommended',
            field=models.ManyToManyField(blank=True, related_name='labs_with_recommended', to='labs.Course'),
        ),
    ]
