# Generated by Django 2.2.6 on 2019-11-02 19:23

from django.db import migrations
from django.db.models import F


def unset_duplicate_nickname(apps, schema_editor):
    Course = apps.get_model("labs", "Course")
    Course.objects.filter(name=F("nickname")).update(nickname=None)


def set_duplicate_nickname(apps, schema_editor):
    Course = apps.get_model("labs", "Course")
    Course.objects.filter(nickname=None).update(nickname=F("name"))


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0009_course_nickname'),
    ]

    operations = [
        migrations.RunPython(unset_duplicate_nickname, set_duplicate_nickname),
    ]
