# Generated by Django 2.2.6 on 2019-11-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0010_auto_20191102_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
