# Generated by Django 2.2.13 on 2021-05-01 15:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0011_auto_20191102_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=5000)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials_written', to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials_set', to='labs.Lab')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric, dashes, and underscores allowed', regex='^[a-zA-Z0-9_\\-]+$')])),
                ('description', models.CharField(max_length=5000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_photos/')),
                ('authors', models.ManyToManyField(related_name='senior_projects_authored', to=settings.AUTH_USER_MODEL)),
                ('labs', models.ManyToManyField(related_name='senior_projects_sponsored', to='labs.Lab')),
            ],
        ),
    ]
