# Generated by Django 2.2.13 on 2021-05-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0012_project_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
    ]
