# Generated by Django 2.1.7 on 2019-03-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(height_field='height', upload_to='club_photos/', width_field='width'),
        ),
    ]
