# Generated by Django 2.1.7 on 2019-04-25 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0002_auto_20190401_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='admins',
            field=models.ManyToManyField(related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
