# Generated by Django 2.1.7 on 2019-03-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20190320_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
