# Generated by Django 2.1.7 on 2019-04-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='height',
        ),
        migrations.RemoveField(
            model_name='club',
            name='width',
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(default='This club page has not yet been filled out.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(height_field='height', null=True, upload_to='club_photos/', width_field='width'),
        ),
    ]
