# Generated by Django 2.2.13 on 2021-05-02 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0007_club_activity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='followers',
            field=models.ManyToManyField(related_name='clubs_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
